[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[project]
name = "hsa_model"
version = "0.0.1"
dependencies = [
    "numpy",
    "pyyaml"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["hsa_model"]